name: matrix
on:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      max-parallel: 1
      matrix:
        version: [one, two, three]	
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
