name: call on me too
on:
  workflow_call:
    
jobs:
  foo:
    runs-on: ubuntu-latest
    concurrency: mutex
    steps:
      - run: sleep 30

  bar:
    runs-on: ubuntu-latest
    concurrency: mutex
    steps:
      - run: sleep 30

  baz:
    runs-on: ubuntu-latest
    concurrency: mutex
    steps:
      - run: sleep 30
