name: call on me four
on:
  workflow_call:
    
jobs:
  example_matrix:
    strategy:
      max-parallel: 1
      matrix:
        version: [one, two, three]	
    runs-on: ubuntu-linux
    steps:
      - run: sleep 30
