name: call on me four
on:
  workflow_call:
    
jobs:
  example_matrix:
    strategy:
      max-parallel: 2
      matrix:
        version: [10, 12, 14]
				
		runs-on: ubuntu-linux
		steps:
		  - run: sleep 30
		
