name: build, test, deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30

  test:
    runs-on: ubuntu-latest
		needs: build
    steps:
      - run: sleep 30

  deploy:
    runs-on: ubuntu-latest
		needs: test
    steps:
      - run: sleep 30
